// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3926.PersonalScienceBot.commands;

import org.usfirst.frc3926.PersonalScienceBot.Robot;
import org.usfirst.frc3926.PersonalScienceBot.helpers.XboxHelper;
import org.usfirst.frc3926.PersonalScienceBot.subsystems.DriveTrain;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class  ManualDrive extends Command {
	DriveTrain driveTrain;
	Joystick xbox;
	
	public static final int
	XBOX_FWD_AXIS = 1,
	XBOX_TURN_AXIS = 4;

    public ManualDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	driveTrain = Robot.driveTrain;
    	xbox = Robot.oi.xbox;
    }

    // Called repeatedly when this Command is scheduled to run
	protected void execute() {
    	double moveVal = XboxHelper.getAxis(1);
    	double rotateVal = XboxHelper.getAxis(4);
    	
    	driveTrain.arcadeDriveOLD(moveVal, rotateVal, true);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	driveTrain.setRawSpeeds(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	driveTrain.setRawSpeeds(0, 0);
    }
}
